version: "3.3"
services:
  bitcoind-node:
    container_name: bitcoind-node
    image: bartoszmilczarek/bitcoind
    environment:
      DISABLEWALLET: 0
      PRINTTOCONSOLE: 1
      RPCUSER: ${RPCUSER:-bitcoinrpc}
      RPCPASSWORD: ${RPCPASSWORD:-bitcoinrpc}
      RPCBIND: 127.0.0.1
      SERVER: 1
      TXINDEX: 1
    ports:
      - "8333:8333"
      - "127.0.0.1:8332:8332"
    volumes:
      - ${BITCOIND_VOLUMES:-/tmp/bitcoind-data}:/bitcoin