version: "3.3"
services:
  bitcoind-node:
    container_name: ${CONTAINER_NAME:-bitcoind-node}
    image: bartoszmilczarek/bitcoind:0.19.1
    environment:
      DISABLEWALLET: 0
      PRINTTOCONSOLE: 1
      RPCUSER: ${RPCUSER:-bitcoinrpc}
      RPCPASSWORD: ${RPCPASSWORD:-bitcoinrpc}
      RPCBIND: ${RPCBIND:-127.0.0.1}
      SERVER: 1
      TXINDEX: 1
      TESTNET: 0
      REGTEST: 0
    ports:
      - "8333:8333"
      - "${RPCBIND}:8332:8332"
    volumes:
      - ${BITCOIND_VOLUMES:-/tmp/bitcoind-data}/${CONTAINER_NAME:-bitcoind-node}:/bitcoin